spring:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
  profiles:
    ### This is the FHIR version. Choose between, dstu2, dstu3, r4 or r5
    active: r4
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT

  batch:
    job:
      enabled: false

hapi:
  fhir:
    defer_indexing_for_codesystems_of_size: 101
    implementationguides:
      -
        url: https://build.fhir.org/ig/hl7dk/dk-medcom/package.tgz
        name: dk.fhir.ig.medcom-core
        version: 0.9

    tester:
      -
          id: home
          name: Local Tester
          server_address: 'http://fhir.medcom.dk:8080/fhir'
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4
      -
          id: global
          name: Global Tester
          server_address: "http://hapi.fhir.org/baseR4"
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4